### ISSUE TITLE
Default empty json-ld

### ISSUE THREAD

**Issue by dmarcelino** [hiimdoublej/django-json-ld#5]
Hello again @hiimdoublej,

Currently when, for example, I use `{% render_json_ld sd %}` in `base.html` and `sd` is empty or non-existant, django will render:
```html
<script type="application/ld+json">""</script>
```
Lets call that option **A**.

I'm wondering if that's the best default behaviour or if we should do something else. Two alternative ideas come to mind:

**B.** Output nothing, so no script tags are printed.

**C.** Output a schema.org `Thing` with the current page URL, something like:
```html
<script type="application/ld+json">
{
   "@context":"https://schema.org"
   "@type":"Thing",
   "url":"http://example.org/",
}
</script>
```

We can also make this behaviour user configurable.

What are your thoughts?

**Comment by hiimdoublej** [comment]
How about making the template tag throw error if provided empty context `sd` ? I think if our users does use this package, they should have a good idea about what kind of structured data they need to render on pages, and it would be up to them to provide a correct structured data. With that in mind, I think the template tag should just throw an error if invalid object is presented to the template tag. This could be done with a settings config specifying what to do when the template tag meets an invalid object. ex: `JSON_LD_INVALID_SD = 'throw'` would throw an error (should be default behavior in my opinion), when `JSON_LD_INVALID_SD = 'silent'` it would fail silently (option B in your case), last when `JSON_LD_INVALID_SD = 'make_thing'` it would do option C. Think option A should be discarded, since a empty JSON_LD serves no purpose. I can implement this if you think this helps address the problem you mentioned :)

**Comment by dmarcelino** [comment]
Hi @hiimdoublej,

Thanks for your input.

### Empty Object: configurable
I guess throwing an error if empty would be option **D**. 🙂 

I'm not too fond of that because I consider a non-existent `sd` a valid scenario which should be translated as either options: B or C. But I see your point of view, and there are moments where one could want a more strict behaviour. In that case I would propose the following configuration options:

 * `JSON_LD_EMPTY_INPUT_RENDERING = 'strict'`: default, raise `TemplateSyntaxError` (D)
 * `JSON_LD_EMPTY_INPUT_RENDERING = 'silent'`: renders nothing (B)
 * `JSON_LD_EMPTY_INPUT_RENDERING = 'generate_thing'`: creates Thing object with URL (C)

I renamed the setting to use "empty" instead of "invalid" because empty is something we are making acceptable in cases B and C.

### Invalid object: error
On the other hand, I believe an "invalid" object like wrong type, or if `json.dumps` throws an error of its own, should be handled and we should raise a `django.template.TemplateSyntaxError` with helpful messages. For this scenario I don't think we need a configuration, if `render_json_ld` receives something it isn't expecting it throws error.

**Comment by hiimdoublej** [comment]
Well thought, think that's a behavior we could both agree on. Let me implement this.

**Comment by dmarcelino** [comment]
Good stuff!

**Comment by hiimdoublej** [comment]
@dmarcelino I coded some quick bits into branch `empty_input_render`. Feel free to check it out and see if it adds the behavior we agreed on correctly, any feedbacks are welcomed. Also feel free to point out any dirty codes you see :)

**Comment by dmarcelino** [comment]
Well done @hiimdoublej!

I made a few comments on your last commit and also made a PR (PR #7) with some small adjustments.

Cheers

**Comment by hiimdoublej** [comment]
Since PR #7, PR #8 are both merged, I now consider this issue addressed and will close this issue. Feel free to reopen this if you feel there's more to discuss regarding this issue.
